name: Test composite action

inputs:
  destination:
    description: 'Destination directory'
    required: true

outputs:
  use-input:
    description: 'Use input'
    value: ${{ inputs.destination }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -x
        ls -la "${GITHUB_ACTION_PATH}"
        ls -la "${GITHUB_ACTION_PATH}/../"
        cd "${GITHUB_ACTION_PATH}" && git log --oneline || true
