name: Test composite action

inputs:
  destination:
    description: 'Destination directory'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      id: first
      env:
        DST: "${{ inputs.destination }}"
      run: |
        set -x
        ls -la ./
        ls -la ../
        echo "${GITHUB_ACTION_PATH}"
        echo "${DST}"
        echo "current-dir=${PWD}" >> "${GITHUB_OUTPUT}"
    - shell: bash
      id: second
      env:
        CURRENT_DIR: "${{ steps.first.outputs.current-dir }}"
      run: |
        echo "current-dir=${CURRENT_DIR}"
