name: Dispatch test call

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        options:
          - main
          - develop
          - feature

jobs:
  run:
    uses: pddg/actions-playground/.github/workflows/test_call.yml@$main
    with:
      version: ${{ inputs.version }}
