name: Use dynamic secret
on:
  push:

jobs:
  test:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        value: [FOO, BAR, NOT_FOUND]
    permissions: {}
    steps:
      - run: |
          echo "The value is ${{ matrix.value }}"
          echo "The secret is ${{ secrets[format('SECRET_{0}', matrix.value)] }}"
