name: Test Native Egress
on:
  push:

jobs:
  run:
    runs-on: ubuntu-24.04-firewall
    permissions: {}
    steps:
      - run: |
          curl -sv -o /dev/null --resolve github.com:443:20.27.177.113 https://github.com/
        env:
          NO_PROXY: "*"
