name: Run MySQL

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb

    steps:
      - name: Install MySQL client 8.0
        run: |
          apt-get update
          apt-get install -y mysql-client-8.0
      - name: Wait for MySQL
        run: |
          until mysql --host=mysql --user=root --password=root -e "SELECT 1"; do
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL is ready!"
