name: Workflow call

on:
  workflow_call:
    inputs:
      version:
        required: false
        default: "main"
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pddg/actions-playground/testcomposite@${{ inputs.version }}
      - run: |
          echo "hello from call_test"