name: Test upload and download artifact

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir artifacts
          echo "Hello world" > artifacts/hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            artifacts/*.txt
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./
      - run: |
          ls -la
